---
image: docker:git

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.1-dind

before_script:
  - apk update && apk add --no-cache docker python3-dev py3-pip docker gcc git curl build-base autoconf automake py3-cryptography linux-headers musl-dev libffi-dev openssl-dev openssh
  - docker info
  - python3 --version

molecule:
  stage: test
  script:
    - pip3 install ansible molecule docker
    - ansible --version
    - cd roles/dubzland-shorewall && molecule test
