- name: ensure shorewall is configured
  template:
    src: "etc/shorewall/{{ item }}.j2"
    dest: "{{ dubzland_shorewall_configuration_root }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - hosts
    - interfaces
    - params
    - policy
    - rules
    - shorewall.conf
    - snat
    - zones
  notify:
    - restart shorewall
  tags:
    - shorewall

- name: ensure shorewall configuration is valid
  command: shorewall check
  changed_when: False
  tags:
    - shorewall
