---
- import_tasks: variables.yml
- import_tasks: packages.yml
- import_tasks: configuration.yml

- name: ensure shorewall is running
  service:
    name: shorewall
    state: started
  tags:
    - shorewall
