---
- name: enable shorewall
  service:
    name: "{{ dubzland_shorewall_service_name }}"
    enabled: yes

- name: restart shorewall
  service:
    name: "{{ dubzland_shorewall_service_name }}"
    state: restarted
